[package]
name = "timestone_tsx_parser"
version = "0.1.0"
edition = "2021"
authors.workspace = true
categories.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
